image:
  file: Dockerfile
ports:
- port: 8050
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
- port: 8889
  onOpen: open-browser
- port: 8890
  onOpen: open-browser
tasks:
- command: cp -r /workspace/regular-invest-maths/.jupyter /home/gitpod/
  command: jupyter notebook
