image:
  file: Dockerfile
ports:
- port: 8050
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
tasks:
- init: /workspace/regular-invest-maths/run.sh
  command: cp -r /workspace/regular-invest-maths/.jupyter /home/gitpod/
